# Goal: do the day-to-day deployment of the site. This is done as the
# "builder" user, not as root. At least, we're going to try to do it like
# this. You need to have an ssh key configured to log in with: this is handled
# in the provision.yml playbook.
---
- name: deploy new version of the project to the server
  hosts: task
  remote_user: builder
  tasks:

    - name: Checkout.
      git:
        accept_hostkey: yes
        dest: "{{ project_path }}"
        repo: https://github.com/nens/raster-tools.git
        version: "master"

    - name: Check whether .venv exists
      stat:
        path: "{{ project_path }}/.venv"
      register: venv_stat

    - name: Create virtualenv.
      command: "virtualenv --python=python3 --system-site-packages {{ project_path }}/.venv"
      ignore_errors: no
      when: venv_stat.stat.exists == False

    - name: Install python packages.
      command: "{{ project_path }}/.venv/bin/pip install -r {{ project_path }}/requirements.txt"
      ignore_errors: no

    - name: Install project.
      command: "{{ project_path }}/.venv/bin/pip install -e {{ project_path }}"
      ignore_errors: no
